# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_pypi:
    name: pypi build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade build setuptools wheel setuptools_scm
          pip install -r requirements.txt
      - name: Build package
        run: |
          python setup.py clean
          python setup.py build bdist_wheel
      - name: Check package
        run: |
          pip install twine
          python -m twine check dist/*

  test_coverage:
    name: test coverage / python-3.9 / ubuntu-latest
    runs-on: ubuntu-latest
    needs: build_pypi
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Test with coverage
        run: |
          pip install pytest
          pytest --cov --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
